### ISSUE TITLE
Wrong number of PDF eigenvectors

### ISSUE THREAD

**Issue by marco-link** [WbWbX/nanoAOD-tools#6]
When processing the `ST_s-channel_4f` and `ST_tW` datasets, all jobs fail with:
```
Traceback (most recent call last):
  File "processors/ST.py", line 435, in <module>
    p.run()
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 234, in run
    eventRange=eventRange, maxEvents=self.maxEntries
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/eventloop.py", line 78, in eventLoop
    ret = m.analyze(e)
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/modules/GenWeightProducer.py", line 67, in analyze
    raise ValueError('wrong number of PDF eigenvectors')
ValueError: wrong number of PDF eigenvectors
```

To reproduce run:
```
python2 processors/ST.py --year 2017 --input=root://cmsxrootd-redirectors.gridka.de//store/user/mlink/WbChargeReco/2022-03-01_v6/mc_2017/ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8/WbChargeReco_mc_2017_2022-03-01_v6/220301_120807/0000/nanox_100.root
```

**Comment by defranchis** [comment]
Solved in https://github.com/WbWbX/nanoAOD-tools/pull/11
