### ISSUE TITLE
Unknown branch nLHEPdfWeight

### ISSUE THREAD

**Issue by marco-link** [WbWbX/nanoAOD-tools#7]
When processing the `WW_TuneCP5`, `WZ_TuneCP5` or `ZZ_TuneCP5` datasets, all jobs fail with:
```
Traceback (most recent call last):
  File "processors/ST.py", line 435, in <module>
    p.run()
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 234, in run
    eventRange=eventRange, maxEvents=self.maxEntries
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/eventloop.py", line 78, in eventLoop
    ret = m.analyze(e)
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/modules/GenWeightProducer.py", line 66, in analyze
    if self.nPDFs > 0 and event.nLHEPdfWeight != self.nPDFs:
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/datamodel.py", line 18, in __getattr__
    return self._tree.readBranch(name)
  File "/work/mlink/wb_scattering/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/treeReaderArrayTools.py", line 76, in readBranch
    raise RuntimeError("Unknown branch %s" % branchName)
RuntimeError: Unknown branch nLHEPdfWeight

```

To reproduce run:
```
python2 processors/ST.py --year 2017 --input=root://cmsxrootd-redirectors.gridka.de//store/user/mlink/WbChargeReco/2022-03-01_v6/mc_2017/WW_TuneCP5_13TeV-pythia8/WbChargeReco_mc_2017_2022-03-01_v6/220301_121902/0000/nanox_28.root
```

**Comment by defranchis** [comment]
Solved in https://github.com/WbWbX/nanoAOD-tools/pull/11
gen weights only evaluated for signal, ttbar, single top, and W+jets
